"""add is_verified to users

Revision ID: 0133f2a23eaf
Revises: 8ded1c8fc3b5
Create Date: 2026-04-22 20:13:39.559854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0133f2a23eaf'
down_revision: Union[str, None] = '8ded1c8fc3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
