"""add scholarship fields

Revision ID: 953081a9bbc4
Revises: 80e1944e59e6
Create Date: 2026-04-25 02:09:02.791213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953081a9bbc4'
down_revision: Union[str, None] = '80e1944e59e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarships', sa.Column('amount_raw', sa.Integer(), nullable=True))
    op.add_column('scholarships', sa.Column('period', sa.String(), nullable=True))
    op.add_column('scholarships', sa.Column('scholarship_type', sa.String(), nullable=True))
    op.add_column('scholarships', sa.Column('eligibility_text', sa.Text(), nullable=True))
    op.add_column('scholarships', sa.Column('cover_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarships', 'cover_image_url')
    op.drop_column('scholarships', 'eligibility_text')
    op.drop_column('scholarships', 'scholarship_type')
    op.drop_column('scholarships', 'period')
    op.drop_column('scholarships', 'amount_raw')
    # ### end Alembic commands ###
